// Generated by Selenium IDE
package java_2lab;
import org.junit.Test;
import org.openqa.selenium.Dimension;
import java.util.*;

public class lab2 extends TestBase {

    @Test
    public void testLogin() {
        openHomePage();
        AccountData user = new AccountData(driver, "Karina", "nchi4792");
        user.login();
    }

    @Test
    public void testAddNote() {
        openHomePage();
        AccountData user = new AccountData(driver, "Karina", "nchi4792");
        user.login();
        String noteText = "Test Karina new lab2";
        NoteData note = new NoteData(driver);
        note.create(noteText);
    }

    public void openHomePage() {
        driver.get("https://diary.anek.ws/");
        driver.manage().window().setSize(new Dimension(1301, 852));
    }
}


