// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testing() {
    driver.get("https://diary.anek.ws/");
    driver.manage().window().setSize(new Dimension(1301, 852));
    driver.findElement(By.id("Nik")).click();
    driver.findElement(By.id("Nik")).sendKeys("Karina");
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("Password")).click();
    driver.findElement(By.id("login_subm")).click();
    driver.findElement(By.id("DiText")).click();
    driver.findElement(By.id("DiText")).sendKeys("New note for lab");
    driver.findElement(By.id("btn_save")).click();
    driver.findElement(By.linkText("Все записи")).click();
    driver.findElement(By.linkText("Править")).click();
    driver.findElement(By.id("DiText")).click();
    driver.findElement(By.id("DiText")).sendKeys("New note for lab. New note lalallalal");
    driver.findElement(By.id("btn_save")).click();
  }
}
