// Generated by Selenium IDE
package java_4lab;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("https://diary.anek.ws/");
    driver.manage().window().setSize(new Dimension(1301, 852));
    driver.findElement(By.linkText("Все записи")).click();
    driver.findElement(By.cssSelector("#dit1041559 .edt")).click();
    driver.findElement(By.id("DiText")).click();
    driver.findElement(By.id("DiText")).sendKeys("Test Karina new lab4");
    driver.findElement(By.id("btn_save")).click();
  }
}
